name: Pipeline
on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master

    workflow_dispatch:

jobs:
    testsuite:
        name: PHP ${{ matrix.php-version }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php-version: ['8.4', '8.5']

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, intl, curl, zlib, dom, openssl, soap, json, simplexml, libxml
                  coverage: none

            - name: Composer Install
              run: |
                composer install --no-progress --no-ansi --no-interaction

            - name: PHPUnit
              run: |
                composer test

            - name: PHPStan
              run: |
                composer phpstan
